import {
  BID_BOT_URLS,
  BLOCKSYNC_GRAPHQL_URLS,
  CLAIM_BOT_URLS,
  IXO_BLOCKCHAIN_RPC_URLS,
  MATRIX_HOMESERVER_URLS,
  ROOM_BOT_URLS,
  SIGN_X_RELAYERS,
} from './urls';

export const CHAIN_ID = process.env.NEXT_PUBLIC_CHAIN_ID ?? 'devnet-1';
export const CHAIN_NETWORK = process.env.NEXT_PUBLIC_CHAIN_NETWORK ?? 'devnet';

export const IXO_BLOCKCHAIN_RPC_URL = IXO_BLOCKCHAIN_RPC_URLS[CHAIN_NETWORK as keyof typeof IXO_BLOCKCHAIN_RPC_URLS];
export const MATRIX_HOMESERVER_URL = MATRIX_HOMESERVER_URLS[CHAIN_NETWORK as keyof typeof MATRIX_HOMESERVER_URLS];
export const MATRIX_ROOM_BOT_URL = ROOM_BOT_URLS[CHAIN_NETWORK as keyof typeof ROOM_BOT_URLS];
export const MATRIX_BID_BOT_URL = BID_BOT_URLS[CHAIN_NETWORK as keyof typeof BID_BOT_URLS];
export const MATRIX_CLAIM_BOT_URL = CLAIM_BOT_URLS[CHAIN_NETWORK as keyof typeof CLAIM_BOT_URLS];
export const SIGN_X_RELAYER_URL = SIGN_X_RELAYERS[CHAIN_NETWORK as keyof typeof SIGN_X_RELAYERS];
export const BLOCKSYNC_GRAPHQL_URL = BLOCKSYNC_GRAPHQL_URLS[CHAIN_NETWORK as keyof typeof BLOCKSYNC_GRAPHQL_URLS];
